# Generated by Django 2.0 on 2017-12-06 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ID', models.SmallIntegerField()),
                ('name_ID', models.CharField(max_length=20)),
                ('status', models.CharField(default='NEVER CONNECTED', max_length=20)),
                ('type', models.CharField(choices=[('CSV', 'CSV'), ('SIEMENS-S7', 'SIEMENS-S7')], max_length=20)),
                ('arguments', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ID', models.SmallIntegerField()),
                ('name_ID', models.CharField(max_length=20)),
                ('status', models.CharField(default='NEVER CONNECTED', max_length=20)),
                ('type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ID', models.SmallIntegerField()),
                ('operator', models.CharField(choices=[('==', '=='), ('<=', '<='), ('>=', '>='), ('<', '<'), ('>', '>'), ('=!', '=!')], max_length=20)),
                ('second_operand', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('sended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_ID', models.SmallIntegerField()),
                ('name_ID', models.CharField(max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('type', models.CharField(choices=[('BOOL', 'BOOL'), ('INTEGER', 'INTEGER'), ('REAL', 'REAL')], max_length=20)),
                ('widget', models.CharField(choices=[('LIGHT', 'LIGHT'), ('SWITCH', 'SWITCH'), ('PARAMETER', 'PARAMETER'), ('DISPLAY', 'DISPLAY')], max_length=20)),
                ('arguments', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Device')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='first_operand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Tag'),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Gateway'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name_ID', 'owner'), ('num_ID', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='gateway',
            unique_together={('name_ID', 'owner'), ('num_ID', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('name_ID', 'owner'), ('num_ID', 'owner')},
        ),
    ]
