# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='device',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='gateway',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tag',
            name='device',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Gateway',
        ),
    ]
